export default {
  HEAT_APPLY: 'HEAT_APPLY',
  HEAT_CAPACITY_UPDATE: 'HEAT_CAPACITY_UPDATE',
  HEAT_RELEASE: 'HEAT_RELEASE',
  HEAT_RESET: 'HEAT_RESET',
  HEATSTORE_UPDATED: 'HEATSTORE_UPDATED',
  GHOST_HEAT_APPLY: 'GHOST_HEAT_APPLY',
}
