export default {
  WEAPON_EQUIP: 'WEAPON_EQUIP',
  WEAPON_UNEQUIP: 'WEAPON_UNEQUIP',
  WEAPON_ALPHA: 'WEAPON_ALPHA',
  WEAPON_DID_ALPHA: 'WEAPON_DID_ALPHA',
  WEAPON_WILL_GROUP_FIRE: 'WEAPON_WILL_GROUP_FIRE'
}
