export default {
  WEAPON_EQUIP: 'WEAPON_EQUIP',
  WEAPON_UNEQUIP: 'WEAPON_UNEQUIP',
  WEAPON_ALPHA: 'WEAPON_ALPHA',
  WEAPON_DID_ALPHA: 'WEAPON_DID_ALPHA',
  WEAPON_GROUP_FIRE: 'WEAPON_GROUP_FIRE',
  WEAPON_WILL_GROUP_FIRE: 'WEAPON_WILL_GROUP_FIRE',
  WEAPON_DID_GROUP_FIRE: 'WEAPON_DID_GROUP_FIRE',
  WEAPON_TOGGLE_GROUP: 'WEAPON_TOGGLE_GROUP',
  WEAPON_COOLDOWN: 'WEAPON_COOLDOWN',
}
